### ISSUE TITLE
use geometry_msg/point?

### ISSUE THREAD

**Issue by BrettRD** [christianrauch/apriltag_msgs#1]
This is a great lib and it works straight out of the gate for me
This is just a note about how some interface decisions have been made in ROS2

The 2d point and pose messages were deprecated in favour of using the 3d messages and setting the unused coordinates to something sensible
https://github.com/ros2/common_interfaces/commit/c994200a9a659dd5fdc65b1cf10d87e248ba1d8d

You can remove the apriltag_msgs/Point message and still be consistent with the conventional usage of geometry_msgs/Point

**Comment by christianrauch** [comment]
I did not use the point message type as I would need to add a new dependency for this trivial two-float message. Do you see a benefit of exchanging the `apriltag_msgs/Point` message with `geometry_msgs/Point`?

**Comment by BrettRD** [comment]
The benefit is quite small, the 2d messages were removed to reduce the number of types that any given geometry visualisation tool would need to cope with.
I'm not aware of any tools that unpack generic messages and visualise them, but the runtime IDL introspection tools are very young

I think `geometry_msgs` is a pretty safe dependency because it's a [dependency](https://index.ros.org/p/common_interfaces/#humble-deps) of `ros_core` via `common_interfaces`; you can't build ros without it

**Comment by christianrauch** [comment]
This may be useful when tools for introspecting and visualising nested messages become available. Until then, I am not sure what the benefit would be. The `AprilTagDetection` message is mostly intended for visualisation and debugging use. I expect people to use the transformations instead.

Do you have a concrete application in mind where `geometry_msgs/Point` would be advantageous? Otherwise, I would postpone this decision until there is a real usecase.
